[platformio]
default_envs = m5stack-cores3

[env]
platform = espressif32@6.13.0
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Unified @ ^0.2.7
  bblanchon/ArduinoJson @ ^6.21.5
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:m5stack-core2]
board = m5stack-core2
upload_speed = 1500000

[env:m5stack-cores3]
board = m5stack-cores3
upload_speed = 921600
